AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Style/Documentation:
  Disable: true

Metrics/ParameterLists:
  Max: 10
